// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArA-LlBuqiAbw4ZNWdtyIbDczU0nNhMXQ',
    appId: '1:998239831749:web:6cc098ecfd9ff70f1392ac',
    messagingSenderId: '998239831749',
    projectId: 'newmybasket',
    authDomain: 'newmybasket.firebaseapp.com',
    storageBucket: 'newmybasket.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtWvTbKjwZBr2oaCqCLJ_8C8p0yT44DSI',
    appId: '1:998239831749:android:f053c7edc6b290321392ac',
    messagingSenderId: '998239831749',
    projectId: 'newmybasket',
    storageBucket: 'newmybasket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF59f7qP_FM819r-YHXtmN1hqzjcqabts',
    appId: '1:998239831749:ios:e77a7b42058c361b1392ac',
    messagingSenderId: '998239831749',
    projectId: 'newmybasket',
    storageBucket: 'newmybasket.appspot.com',
    iosBundleId: 'com.example.mybasket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF59f7qP_FM819r-YHXtmN1hqzjcqabts',
    appId: '1:998239831749:ios:e77a7b42058c361b1392ac',
    messagingSenderId: '998239831749',
    projectId: 'newmybasket',
    storageBucket: 'newmybasket.appspot.com',
    iosBundleId: 'com.example.mybasket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArA-LlBuqiAbw4ZNWdtyIbDczU0nNhMXQ',
    appId: '1:998239831749:web:64cd8e3dda19490c1392ac',
    messagingSenderId: '998239831749',
    projectId: 'newmybasket',
    authDomain: 'newmybasket.firebaseapp.com',
    storageBucket: 'newmybasket.appspot.com',
  );
}
